apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: app1
  janus-idp.io/tekton: app1
  backstage.io/kubernetes-id: app1
  backstage.io/kubernetes-namespace: rhtap-app1 
  app.kubernetes.io/part-of: app1
resources: 
- deployment.yaml
- route.yaml
- service.yaml
